### ISSUE TITLE
<app_name_storage> or <app_name>?

### ISSUE THREAD

**Issue by eduardsik** [VitorHugoAguiar/VitiBot#9]
Hello Hugo,

please take a look on this lines. The <app_name_storage> is good here or need just <app_name>?

dokku run <app_name_storage> python manage.py db init    --directory '/storage/migrations'
dokku run <app_name_storage> python manage.py db migrate --directory '/storage/migrations'
dokku run <app_name_storage> python manage.py db upgrade --directory '/storage/migrations'

thanks,
Eduard

**Comment by VitorHugoAguiar** [comment]
Hi eduardsik 
You are right. I already changed the readme. Thanks
